#page title
page_title                                : "Pilot: Habit & Goal Tracker"                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1576506049                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "Pilot: Habit & Goal Tracker"                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Build Habits and Goals with pleasure.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : VolcanoUniversum
your_link                                 : https://volcanouniversum.github.io/
your_city                                 :
email_address                             : volcano.universum@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : VolcanoUnivers
github_username                           : VolcanoUniversum/HabitPilot
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Unlimited
    description                           : You are able to create unlimited amount of Habits without any restrictions.
    fontawesome_icon_name                 : tasks

  - title                                 : Synchronization
    description                           : All your Habits and progresses are seamlessly synchronize across your devices.
    fontawesome_icon_name                 : cloud

  - title                                 : Customizable
    description                           : You can create different types of Habits - track your sleeping, budget or mood.
    fontawesome_icon_name                 : edit

  - title                                 : Free
    description                           : Unlimited access to all features without any payment.
    fontawesome_icon_name                 : credit-card

  - title                                 : Privacy
    description                           : All your settings & data are stored securely on your devices. Pilot does not use third-party analytics or ads.
    fontawesome_icon_name                 : user-secret


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/lucas-favre-JnoNcfFwrNA-unsplash.jpg # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FEEFD6"
feature_icons_background_color            : "#FBA900"

social_icons_foreground_color             : "#1f0d68"
social_icons_background_color             : "#d1d0e1"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
  cache_location: "./docs/site/.sass-cache"

# Exclude these files from your production _site
exclude:
 - "*.erb"

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown